/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vblank_Native */

#ifndef _Included_vblank_Native
#define _Included_vblank_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vblank_Native
 * Method:    calc
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_vblank_Native_calc
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
